DATA_FS:
  SAVE_DIR: "saved_models/"
  OUTPUT_DIR : "output_bflies/"
DATASET:
  IMAGE_SIZE: 64
  BATCH_SIZE: 128
  params:
    shuffle: True
    num_workers: 6
GEN_MODEL:
  FM:
    NAME: "fm_model_bflies.pth"
    TIME_MAX_POS: 1000    #For UNet this variable match  TOTAL_TIME_STEPS
    TRAIN:
      LR: 0.0001
      EPOCHS: 1000
  DDPM:
    NAME: "ddpm_model_bflies.pth"
    TIMESTEPS: 1000 # Define number of diffusion timesteps
    TRAIN:
      LR: 0.0001
      EPOCHS: 500
UNET:
  NUM_RES_BLOCKS: 1
  INPUT_CHANNELS: 3
  OUTPUT_CHANNELS: 3
  BASE_CH: 64  # 64, 128, 256, 512
  BASE_CH_MULT: [1, 2, 4, 8] # 32, 16, 8, 4
  APPLY_ATTENTION: [False, True, True, False]
  DROPOUT_RATE: 0.1
  TIME_EMB_MULT: 4 # 128
  TOTAL_TIME_STEPS: 1000
  TIME_EMB_MAX_FREC: 10000
SAMPLING:
  NUM_SAMPLES: 16
  STEPS: 1000
PLOT:
  NAME: "bflies_over_time_{}.gif"
  FPS: 5
  PLOT_STEPS: 20