DATASET:
  IMAGE_SIZE: 64
  BATCH_SIZE: 32
  params:
    shuffle: True
    num_workers: 6
MODEL:
  MODEL_SAVE_DIR: "saved_models"
  OUTPUT_DIR : "images"
  MODEL_NAME: "fm_unet_model.pth"
  NUM_RES_BLOCKS: 1
  INPUT_CHANNELS: 3
  OUTPUT_CHANNELS: 3
  BASE_CH: 64  # 64, 128, 256, 512
  BASE_CH_MULT: [1, 2, 4, 8] # 32, 16, 8, 4
  APPLY_ATTENTION: [False, True, True, False]
  DROPOUT_RATE: 0.1
  TIME_EMB_MULT: 4 # 128
  TIME_EMB_MAX_POS: 1000
TRAIN:
  LR: 0.0001
  EPOCHS: 5000
SAMPLING:
  NUM_SAMPLES: 16
  STEPS: 1000
PLOT:
  NAME: "butterflies_over_time.gif"
  FPS: 5
  PLOT_STEPS: 20